name: CI Pipeline & Docker Build (Final)

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  # GANTI INI: Nama Repository di Docker Hub
  IMAGE_NAME: "msml"
  EXPERIMENT_NAME: "CI_Experiment"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    # Load Secrets ke Environment Variables
    env:
      DAGSHUB_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
      DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
      MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
      MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      # =========================
      # 1. CHECKOUT REPOSITORY
      # =========================
      - name: Checkout repository
        uses: actions/checkout@v3

      # =========================
      # 2. SETUP PYTHON
      # =========================
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      # =========================
      # 3. INSTALL DEPENDENCIES
      # =========================
      - name: Install dependencies
        run: |
          pip install \
            mlflow \
            pandas \
            numpy \
            scikit-learn \
            dagshub \
            seaborn \
            matplotlib \

      # =========================
      # 4. RUN MODELING SCRIPT
      # =========================
      - name: Run Modeling & Save Run ID
        working-directory: ./MLProject
        run: |
          mlflow run . --env-manager=local

      # =========================
      # 5. LOGIN DOCKER HUB
      # =========================
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # =========================
      # 6. BUILD & PUSH DOCKER IMAGE
      # =========================
      - name: Build and Push Docker Image
        working-directory: ./MLProject
        run: |
          # Baca Run ID dari file txt (Hasil dari langkah 4)
          RUN_ID=$(cat run_id.txt)
          echo "Detected Run ID: $RUN_ID"

          # Hardcode nama image agar PASTI BENAR: tickelboy/msml:latest
          FULL_IMAGE_NAME="tickelboy/${{ env.IMAGE_NAME }}:latest"
          
          echo "Building Image: $FULL_IMAGE_NAME"

          # Build Docker Image menggunakan MLflow
          mlflow models build-docker \
            -m "runs:/$RUN_ID/model_final" \
            -n "$FULL_IMAGE_NAME" \
            --enable-mlserver

          # Push ke Docker Hub
          echo "Pushing to Docker Hub..."
          docker push "$FULL_IMAGE_NAME"
